apiVersion: v1    # Made it only v1 as apps/v1 was giving error
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080