version: '3.4'

services:
  shoppingdb:
    image: mongo

  #catalog12express:
  #  image: mongo-express

  shopping.api:
    image: ${DOCKER_REGISTRY-}shoppingapi
    build:
      context: .
      dockerfile: Shopping.API/Dockerfile

volumes:
  mongo_data:

#networks:
#  mongo-network: