version: '3.4'

services:
  shoppingdb:
    container_name: shoppingdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  shopping.api:
    container_name: shopping.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://admin:password@shoppingdb:27017"
    depends_on:
      - shoppingdb
    ports:
      - "8000:80"

  shopping.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ShoppingAPIUrl=http://shopping.api"
    ports:
      - "8001:80"